---
  - name: "Download PiVPN installer"
    get_url:
      url: https://install.pivpn.io
      dest: ~/install-pivpn.sh
      mode: 0740

  - name: Set unattended conf for pivpn
    become: True
    template:
      src: "unattended_wireguard.conf.j2"
      dest: "~/unattended_wireguard.conf"
      owner: root
      group: root
      mode: 0644
    register: unattendedconf

  - name: Install PiVPN
    shell: "~/install-pivpn.sh --unattended "
    when: unattendedconf.changed

  - name: add templates
    ansible.builtin.template:
      src: /mytemplates/foo.j2
      dest: /etc/file.conf
      owner: bin
      group: wheel
      mode: '0644'
